{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fluxion.fullname" . }}
  labels:
    {{- include "fluxion.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.argocd.syncWave }}
    {{- include "fluxion.argocd.syncWave" (dict "wave" .Values.argocd.syncWave.ingress) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
      {{- if $.Values.ingress.tls.secretName }}
      secretName: {{ $.Values.ingress.tls.secretName }}
      {{- else }}
      secretName: {{ include "fluxion.fullname" $ }}-tls
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "fluxion.api.fullname" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
