{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluxion.postgresql.serviceName" . }}
  labels:
    {{- include "fluxion.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- with .Values.postgresql.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.argocd.syncWave }}
    {{- include "fluxion.argocd.syncWave" (dict "wave" .Values.argocd.syncWave.postgresql) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "fluxion.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
