{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluxion.serviceAccountName" . }}
  labels:
    {{- include "fluxion.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.argocd.syncWave }}
    {{- include "fluxion.argocd.syncWave" (dict "wave" .Values.argocd.syncWave.namespace) | nindent 4 }}
  {{- end }}
{{- end }}
